---
collections:
  - name: ansible.posix
    version: 1.1.1
  - name: community.crypto
    version: 1.1.1
  - name: community.general
    version: 2.0.1
  - name: community.postgresql
    version: 1.0.0
  - name: awx.awx
    version: 17.1.0
  - name: community.docker
    version: 1.5.0
  - name: community.mysql
    version: 1.2.0
  - name: community.mongodb
    version: 1.2.1
  - name: ansible.netcommon
    version: 2.0.0
  - name: community.grafana
    version: 1.2.1
