---
dockerhub_version: "{{ lookup('file', playbook_dir + '/../VERSION') }}"

awx_image: "awx"
redis_image: "redis"

postgresql_version: "10"
postgresql_image: "postgres:{{postgresql_version}}"

create_preload_data: false
compose_start_containers: true
